---
# tasks file for deploy-instance
- name: deploy new instance
  os_server:
    cloud: "{{user_name}}"
    name: "{{item.instance_name}}"
    image: "{{item.image_name}}"
    flavor: "{{item.flavor_name}}"
    key_name: "{{item.key_name}}"
    network: "{{item.network_name}}"
    auto_ip: "{{item.pub_ip | default ('no')}}"
    state: "{{state}}"
    meta: 
     hostname: "{{item.instance_name}}"
     group_name: "{{item.group_name | default (omit)}}"
  with_items:
     - "{{instance_info}}"
  register: os_instance

- name: temp debug for tshoot
  debug:
    msg: "deployed with {{item.server.public_v4}}"
  with_items: "{{os_instance.results }}"
  when: state == "present"  

- name: add temp host inventory
  add_host:
     name: "{{item.server.name}}"
     groups: "{{item.server.metadata.group_name}}"
     ansible_ssh_host: "{{item.server.public_v4 if item.server.public_v4 is defined else item.server.private_v4}}"
  with_items: "{{os_instance.results }}"
  when: state == "present"
