---
# tasks file for create-user
- name: create new user
  os_user: 
    cloud: "{{admin_user}}"
    name: "{{new_user_name}}"
    password: "{{new_user_password}}"
    email: "{{new_user_email}}"
    state: "{{state}}"
    domain: default
    default_project: "{{project_name}}"
- name: Ensure project user association
  os_user_role:
    cloud: "{{admin_user}}"
    state: "{{state}}"
    user: "{{new_user_name}}"
    project: "{{project_name}}"
    role: _member_
  ignore_errors: yes
