---
# tasks file for nodjs-npm-deploy
- name: nmp deploy
  shell: |
      npm install
  args:
    chdir: "{{dest_path}}/simple-app"
  register: output

- debug: var=output

- name: nodejs
  shell: |
    NODE_ENV={{env_name}} PUBLIC_URL=0.0.0.0 node server.js &
  args:
    chdir: "{{dest_path}}/simple-app"
  async: 1
  poll: 0
  register: js_result

- debug: var=js_result     
