---
ec2_server_instcount: 1
ec2_instance_type: t2.micro
ec2_server_image: 'ami-2c95344f' #rhel 7 
#'ami-f068a193' # Centos 7 in ap-southeast-1
ec2_server_region: 'ap-southeast-1'
ec2_server_pem_path: ''
ec2_server_group_name: 'ec2_server_hosts'

ec2_server_keypair: ''

ec2_assign_public_ip: true
ansible_ec2_use_public_ip: true

required_vars:
  - ec2_server_region
  - ec2_server_security_group
  - ec2_server_name
  - ec2_server_image
  - ec2_server_keypair
  - ec2_instance_type
  - ec2_vpc_subnet_id
  
name_start_index: 0
name_prefix: aws-test

#ec2_tags: