- hosts: all
  become: true
  tasks: 
    - name: register to RHN
      redhat_subscription:
        state: present
        username: "ryan.ye@redhat.com"
        password: "N0thing,10"
        auto_attach: true

    - name: update all packages
      yum:
        name: "*"
        state: latest
