---
- name: Install package
  yum:
    name: "{{ package_name }}"
    state: latest
    skip_broken: yes
    update_cache: yes

#- name: Check whether package is installed
#  shell: rpm -qi "{{ item }}"
#  with_item: "{{ package_name }}"
#  register: output

#- debug: msg="{{ output.stdout }}"

- name: Start and enable service
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes
  when: service_name is defined
  ignore_errors: yes
