---
- name: Install package
  yum:
    name: "{{ package_name }}"
    state: latest

- name: Check whether package is installed
  shell: rpm -qi "{{ package_name }}"
  register: output

- debug: msg="{{ output.stdout }}"

- name: Start and enable service
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes