---
# tasks file for manage-security-group-rules
- name: add new port
  os_security_group_rule:
    cloud: "{{user_name}}"
    security_group: "{{sg_name}}"
    protocol: "{{sg_proto}}"
    port_range_min: "{{sg_port_min | default(omit)}}" 
    port_range_max: "{{sg_port_max | default(omit)}}"
    remote_ip_prefix: "{{sg_remote_ip}}"
    state: "{{state}}"
    remote_group: "{{remote_group | default(omit)}}" 

