---
- name: Provision EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    - nodejs_keypair: ryanymt-rh
    - nodejs_instcount: 1
    - nodejs_inst_name: "nodejs"
    - nodejs_image: ami-6966b80a
    - nodejs_subnet: subnet-24aa677d
    - ec2_server_keypair: "{{ nodejs_keypair }}"
    - ec2_server_security_group: web-svc
    - ec2_vpc_subnet_id: "{{ nodejs_subnet }}"
    - ec2_server_group_name: webservers
    - ec2_server_image: "{{ nodejs_image }}" # Centos7
    - ec2_server_instcount: "{{ nodejs_instcount }}"
    - name_start_index: 10
    - name_prefix: "Certis"
    - ec2_assign_public_ip: true
    - ec2_inst_name: "{{ project_name + '_demo' }}"

    #Defaults in role
    #ec2_server_image: 'ami-f068a193' # Centos 7 in ap-southeast-1
    #ec2_server_region: ap-southeast-1
    #ec2_instance_type: t2.micro

    - ec2_tags:
        Env: Demo 
        Project: Certis
        Vendor: RedHat
        Role: nodejs

# Tower variables
    - tower_inventory_name: "{{name_prefix}}"
    - tower_host: lab05-ip01.monsoonknowledge.com
    - tower_username: "admin"
    - tower_password: "N0thing10"


  roles:
    - { role: create-ec2 }
    - { role: add-to-tower, when: tower_host is defined }

- name: Package Installation
  hosts: new_servers
  #become: yes
  # package installation
  vars: 

    - ansible_ssh_private_key_file: /root/ryanymt.pem
    - ansible_remote_user: root
    - package_name: 
         - nodejs*
         - git
         - npm

  roles: 
    - { role: enable-epel-repo }
    - { role: install-package, when: package_name is defined }
